Convert FLINT implementation life-cycle to markdown
moja-global/Google_Season_of_Documentation pull request #26
Opened 2021-07-10 17:05 UTC by soumik2012

This PR converts the [Google Doc ](https://docs.google.com/document/d/1vNSvKFERxvgUjEpBcG18dGaHhNnBC7hdPkkkcKBkeic/edit#heading=h.2f13emraymka)to Markdown 👍🏻

2021-07-10 17:08 UTC, soumik2012 commented
Hello @aornugent Can you please have a look at this?

2021-07-10 22:59 UTC, aornugent reviewed
Looking good, thanks @soumik2012

Could you please fix a typo in the file name (plain -> plan) and break the subheadings for each sprint over two lines? ✌️

2021-07-11 08:46 UTC, soumik2012 commented
@aornugent You can check the PR i have modify the files

2021-07-11 08:57 UTC, aornugent commented on Planning/generic_plan_in_sprints.md
> +### Sprint 1:  Month 3 to 7: Low accuracy working concept
@soumik2012 - sorry I meant break it into two parts on separate lines. For example:
```
## Sprint 1
## Month 3 to 7: Low accuracy working concept
```

2021-07-11 09:07 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +### Sprint 1:  Month 3 to 7: Low accuracy working concept
@aornugent  Done!! 💯

2021-07-11 09:14 UTC, soumik2012 commented
@aornugent Is that right now ??

2021-07-11 14:34 UTC, soumik2012 commented
@aornugent Done !! 🧇

2021-07-11 17:53 UTC, HarshCasper requested changes

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +Below the implementation of a FLINT based MRV system is layed out in phases (aka sprints) of 5 months.
Replace with `The implementation of a FLINT based MRV system is laid out in phases (aka sprints) of 5 months.`

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +### Preparation phase:
Add a line break

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Prioritise the most common existing disturbances (e.g. degradation)
Add proper full stops on every pointers

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +### Sprint 1:
Add a line break after this

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements.
Add proper full stops on every pointers

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Others as required
Add proper full stops on every pointer

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
Add proper full stops on every pointer

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +### Sprint 6:
Add a line break

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
Add proper full stops on every pointer

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +### Sprint 5:
Add a line break

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
Add proper full stops on every pointer

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
Add proper full stops on every pointer

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +### Sprint 4:
Add a line break

2021-07-11 17:53 UTC, HarshCasper commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
Add proper full stops on every pointer

2021-07-12 04:54 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +### Preparation phase:
@HarshCasper done!!

2021-07-12 04:54 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +- Prioritise the most common existing disturbances (e.g. degradation)
@HarshCasper Done!!

2021-07-12 04:54 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
@HarshCasper Done!!

2021-07-12 04:55 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +- Uncertainty analysis and resulting suggestions for improvements
@HarshCasper Done !!

2021-07-12 04:55 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +### Sprint 6:
@HarshCasper Done !!

2021-07-12 04:55 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +Below the implementation of a FLINT based MRV system is layed out in phases (aka sprints) of 5 months.
@HarshCasper Done!

2021-07-12 04:55 UTC, soumik2012 commented on Planning/generic_plan_in_sprints.md
> +### Sprint 4:
Done!!

2021-07-12 06:24 UTC, HarshCasper approved these changes

2021-07-12 06:25 UTC, merged

2021-07-12 06:25 UTC, HarshCasper commented
Thanks @soumik2012 for contributing to @moja-global